pub mod context;
pub mod dim;
pub mod eval;
mod expr;
pub mod unit;
pub mod fmt;
pub mod gen_expr;
mod parser;
pub mod rational;
pub mod repl;
mod rule;
mod search;
mod to_tex;
pub mod random_search;
pub mod token;
pub mod training_data;
pub mod validate;

pub use context::{Context, DimEnv, DimError, DimOutcome, EqualityResult, format_dim_error, is_zero};
pub use dim::{BaseDim, Dimension};
pub use eval::{eval_f64, free_vars, spot_check, SpotCheckFailure};
pub use unit::Unit;
pub use expr::*;
pub use fmt::{fmt_colored, Colored};
pub use parser::{parse_expr, ParseError};
pub use rule::*;
pub use search::*;
pub use to_tex::ToTex;
