"""Vocabularies for encoder (input tokens) and decoder (actions).

Reads vocab.json emitted by gen_data to stay in sync with Rust definitions.
"""

from __future__ import annotations

import json
import os


def _load_vocab_json(data_dir: str) -> dict:
    path = os.path.join(data_dir, "vocab.json")
    with open(path) as f:
        return json.load(f)


class EncoderVocab:
    """Maps input token strings to integer IDs.

    Reads encoder_tokens from vocab.json (generated by gen_data).
    Layout: [PAD=0, token_0=1, token_1=2, ...]
    """

    PAD = 0

    def __init__(self, data_dir: str = "data_training"):
        vocab = _load_vocab_json(data_dir)
        self._token_to_id: dict[str, int] = {"<PAD>": 0}
        self._id_to_token: list[str] = ["<PAD>"]
        for tok in vocab["encoder_tokens"]:
            idx = len(self._id_to_token)
            self._token_to_id[tok] = idx
            self._id_to_token.append(tok)

    def encode(self, token: str) -> int:
        """Convert a token string to its integer ID. Returns PAD for unknown."""
        return self._token_to_id.get(token, self.PAD)

    def decode(self, token_id: int) -> str:
        if 0 <= token_id < len(self._id_to_token):
            return self._id_to_token[token_id]
        return "<PAD>"

    def size(self) -> int:
        return len(self._id_to_token)


class DecoderVocab:
    """Maps decoder tokens (BOS, STOP, RULE_n, POS_n) to integer IDs.

    Reads total_directions from vocab.json (generated by gen_data).
    Layout: [PAD=0, BOS=1, STOP=2, RULE_0..RULE_{n-1}, POS_0..POS_{m-1}]
    """

    PAD = 0
    BOS = 1
    STOP = 2

    def __init__(self, data_dir: str = "data_training", max_positions: int = 64):
        vocab = _load_vocab_json(data_dir)
        self._num_rules = vocab["total_directions"]
        self._max_positions = max_positions

    @property
    def rule_offset(self) -> int:
        return 3  # after PAD, BOS, STOP

    @property
    def pos_offset(self) -> int:
        return 3 + self._num_rules

    def encode_rule(self, rule_dir: int) -> int:
        return self.rule_offset + rule_dir

    def encode_pos(self, pos: int) -> int:
        return self.pos_offset + min(pos, self._max_positions - 1)

    def decode(self, token_id: int) -> tuple[str, int]:
        """Returns (type, value) where type is 'PAD', 'BOS', 'STOP', 'RULE', or 'POS'."""
        if token_id == self.PAD:
            return ("PAD", 0)
        if token_id == self.BOS:
            return ("BOS", 0)
        if token_id == self.STOP:
            return ("STOP", 0)
        if self.rule_offset <= token_id < self.pos_offset:
            return ("RULE", token_id - self.rule_offset)
        if self.pos_offset <= token_id < self.pos_offset + self._max_positions:
            return ("POS", token_id - self.pos_offset)
        return ("PAD", 0)

    def size(self) -> int:
        return 3 + self._num_rules + self._max_positions
